# Generated by Django 4.0.5 on 2022-06-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoFinalApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('usuario', models.CharField(max_length=25)),
                ('edad', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Jugadores',
            },
        ),
        migrations.AlterModelOptions(
            name='servidor',
            options={'verbose_name_plural': 'Servidores'},
        ),
    ]
