# Generated by Django 4.0.5 on 2022-07-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoFinalApp', '0004_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='juegoServer',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
